spring:
  application:
    name: app-provider
# dubbo
dubbo :
  application :
    id: app-provider
    name: app-provider
    owner: konghang
    qos-enable: false
    qos-port: 22222
    version: 1.0.0
  protocol:
    prot: 20880
    name: dubbo
    id: dubbo
    status: server
  registry:
    address: zookeeper://127.0.0.1:2181
    id: app-provider
  scan:
    basePackages: com.ysla.provider.module
management:
  # Enables Dubbo All Endpoints
  endpoint:
    dubbo:
      enabled: true
      dubbo-shutdown:
        enabled: true
      dubbo-configs:
        enabled: true
      dubbo-services:
        enabled: true
      dubbo-references:
        enabled: true
      dubbo-properties:
        enabled: true
  # Dubbo Health
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool