server:
  #定义启动访问端口号
  port: 8080
  error:
    include-stacktrace: ALWAYS

spring:
  application:
    name: app-web
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    # 开发阶段务必关闭缓存 (=false)
    cache: false

application:
  version: 1.0.0

com:
  ysla:
    #swagger属性配置
    swagger:
      basePackage: com.ysla.web.controller
      title: 使用Swagger2构建RESTful APIs
      description: 更多文章请关注：http://me.ml520.top
      termsOfServiceUrl: http://me.ml520.top
      contactName: KongHang
      contactUrl: ${com.ysla.swagger.termsOfServiceUrl}
      contactMail: kong.hh@live.com
      version: 1.0.0
    qiniu:
      ak: ENC(D/VuDxw4sYcJTnPwyqkP9C/AuT9CHO3/lKxVf5FGHGWtlaXOGl9UdujhKnCZZVGNxvpVWjs2QSw=)
      sk: ENC(kDoLh2ZjFnfyaRIltwixmBzrh9SqfsbEA2ev5SuUVwc3Ymoc46TR5cGb3p5R5Jv5lnqY4gNRHRU=)
      bucket: ENC(jqSA7eF9y3VoHbQ9edltnqb4knRsh1Js)

# dubbo
dubbo :
  application :
    id: app-web
    name : app-web
  registry :
    id: app-web
  #scan:
    #basePackages: com.ysla.web.controller
# Dubbo Endpoint (default status is disable)
endpoints:
  dubbo:
    enabled: true